version: "3.9"

services:
  messages:
    build:
      context: ./
      dockerfile: Dockerfile
    image: i_messages
    container_name: "c_messages"
    ports:
      - ${PORT_SERVER}:3000
    volumes:
      - ./src:/messages/src
      - ./bin:/messages/bin
      - ./frontend:/messages/frontend
      - ./package.json:/messages/package.json
    environment:
      REDIS_URI: "redis://redis:6379"
      MONGO_URI: "mongodb://mongo:27017/messages"
      NODE_ENV: "${NODE_ENV}"
      AUTH_TOKEN_SECRET: ${AUTH_TOKEN_SECRET}

  mongo:
    image: mongo
    container_name: "c_messages_mongo"
    restart: always
    