version: "3.9"

services:
  messages:
    build:
      context: ./
      dockerfile: Dockerfile
    image: i_messages
    container_name: "c_messages"
    ports:
      - ${PORT_SERVER}:3000
    volumes:
      - ./src:/messages/src
      - ./package.json:/messages/package.json
    environment:
      REDIS_URI: "redis://redis:${PORT_REDIS}"
      MONGO_URI: "mongodb://mongo:${PORT_MONGO}/messages"
      NODE_ENV: "${NODE_ENV}"
      PORT_SERVER: ${PORT_SERVER}
  
  mongo:
    image: mongo
    container_name: "c_messages_mongo"
    restart: always
    ports:
      - ${PORT_MONGO}:27017

  # redis:
  #   image: redis:6.2-alpine
  #   container_name: "c_messages_redis"
  #   restart: always
  #   ports:
  #     - ${PORT_REDIS}:6379